# @package algo
_target_: algo.ddpg.DDPGAgent
name: ddpg
obs_type: ${suite.obs_type}
obs_shape: ??? # to be specified later
action_dim: ??? # to be specified later
device: ${device}
lr: 1e-4
# lr: 3e-4
batch_size: 256
nstep: 3
critic_target_tau: 0.01
# critic_target_tau: 0.005
update_every_steps: 2
use_tb: ${use_tb}
num_expl_steps: 2000
# num_expl_steps: 5000
critic_use_ln: false
critic_hidden_dims: [1024, 1024]
# critic_hidden_dims: [512, 512, 256]
critic_spectral_norms: [false, false]
actor_use_ln: true
actor_hidden_dims: [1024, 1024]
# actor_hidden_dims: [256, 256] # [256, 256, 256]
actor_spectral_norms: [false, false]
feature_dim: 50
stddev_schedule: 'linear(1.0,0.1,500000)' # for medium envs like quadruped_walk
# stddev_schedule: 'linear(1.0,0.1,100000)' # for easy envs like walker walk
stddev_clip: 0.3