# @package algo
_target_: algo.sac.SACAgent
name: sac
obs_type: ${suite.obs_type}
obs_shape: ??? # to be specified later
action_dim: ??? # to be specified later
action_range: ??? # to be specified later

device: ${device}
lr: 1e-4
batch_size: 1024
nstep: 1
log_std_bounds: [-5, 2]
critic_target_tau: 5e-3
critic_use_ln: false
#critic_hidden_dims: [1024, 1024] #[512, 512, 256]
critic_hidden_dims: [1024, 1024] #[512, 512, 256]
critic_spectral_norms: [false, false]
# actor_hidden_dims: [1024, 1024] #[256, 256, 256]
actor_hidden_dims: [1024, 1024] #[256, 256, 256]
feature_dim: 50
actor_use_ln: false
actor_spectral_norms: [false, false]
num_expl_steps: 5000
init_temperature: 0
update_every_steps: 2
use_tb: ${use_tb}