
# @package agent
_target_: agent.boosting.BoostingAgent
name: boosting
batch_size: ${algo.batch_size}
task: ${suite.task}
device: ${device}
feature_dim: ???
algo: ${algo}
representation: rl_encoder

#disc_hidden_dim: 512
disc_hidden_dim: 64
disc_type: ${disc_type}
disc_update_iter: ${disc_iter}
n_learners: ${n_learners}
discount: ${discount}
divergence: rkl

mixin_schdl: constant_1.0 # here no expert is used
